name: Node

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  affected:
    uses: GoogleCloudPlatform/cloud-samples-tools/.github/workflows/affected.yaml@9ee708234e240605d96e78f652c333ed6aa95a23 # v0.4.0
    permissions:
      statuses: write
    with:
      head-sha: ${{ github.event.pull_request.head.sha || github.sha }}
      config-file: .github/custard/node/config.jsonc
      custard-version: v0.4.0

  lint:
    needs: affected
    runs-on: ubuntu-latest
    permissions:
      statuses: write
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
      - name: Setup Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 24
      - name: Setup tooling
        run: bash .github/custard/node/setup.sh
      - name: Run lint
        run: bash .github/custard/map.sh ${{ env.SCRIPT }} ${{ env.PATHS }}
        env:
          SCRIPT: .github/custard/node/lint.sh
          PATHS: ${{ needs.affected.outputs.paths }}
