name: test-workflows

on:
  push:
    branches:
      - main
    paths:
      - .github/custard/**
      - .github/workflows/**
  pull_request:
    paths:
      - .github/custard/**
      - .github/workflows/**

jobs:
  lint-pass:
    uses: ./.github/workflows/lint.yaml
    with:
      head-sha: ${{ github.event.pull_request.head.sha || github.sha }}
      paths: |
        [
          ".github/custard/test/node/lint-pass",
          ".github/custard/test/python/lint-pass"
        ]

  # Failures should be tested one by one, since as long as there is one,
  # the whole job will fail.
  lint-fail-node:
    uses: ./.github/workflows/lint.yaml
    with:
      head-sha: ${{ github.event.pull_request.head.sha || github.sha }}
      paths: '[".github/custard/test/node/lint-fail"]'
      expect-failure: true

  lint-fail-python:
    uses: ./.github/workflows/lint.yaml
    with:
      head-sha: ${{ github.event.pull_request.head.sha || github.sha }}
      paths: '[".github/custard/test/python/lint-fail"]'
      expect-failure: true
